# Site settings
title: Giuseppe Vallarelli
author: "Giuseppe Vallarelli"
header-img: img/home-bg.jpg
copyright_name: Giuseppe Vallarelli
description: ""
baseurl: ""
url: http://gvallarelli.github.io
github_username:  gvallarelli
linkedin_username: giuseppevallarelli

# Build settings
encoding: UTF-8
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
